import * as fs from 'fs';
import * as path from 'path';
import { TOMCAT_DEBUG_CONFIG_NAME, START_TASK_NAME, STOP_TASK_NAME } from './constants';

export interface ConfigWriterOptions {
    tomcatHome: string;
    tomcatBaseDir: string;
    projectRoot: string;
    vscodeDir: string;
    httpPort: number;
    debugPort: number;
    contextPath: string;
    resolvedDocBase: string;
    resolvedSourceBase: string;
    resolvedClassesBase: string;
    jndiResources: any[];
    javaOpts: string;
    colorizeLogs: boolean;
    autoOpenBrowser: boolean;
}

// ---------------------------------------------------------------------------
// Tomcat Runtime Directory Setup
// ---------------------------------------------------------------------------

export function setupTomcatBaseDir(tomcatHome: string, tomcatBaseDir: string): void {
    const confDir = path.join(tomcatBaseDir, 'conf');
    const sourceConfDir = path.join(tomcatHome, 'conf');

    if (!fs.existsSync(tomcatBaseDir)) {
        fs.mkdirSync(tomcatBaseDir, { recursive: true });
    }

    fs.cpSync(sourceConfDir, confDir, { recursive: true });

    ['logs', 'temp', 'work', 'webapps'].forEach(dir => {
        const dirPath = path.join(tomcatBaseDir, dir);
        if (!fs.existsSync(dirPath)) {
            fs.mkdirSync(dirPath);
        }
    });
}

// ---------------------------------------------------------------------------
// server.xml
// ---------------------------------------------------------------------------

export function writeServerXml(tomcatBaseDir: string, httpPort: number): void {
    const serverXmlPath = path.join(tomcatBaseDir, 'conf', 'server.xml');
    if (fs.existsSync(serverXmlPath)) {
        let serverXml = fs.readFileSync(serverXmlPath, 'utf8');
        serverXml = serverXml.replace(
            /(<Connector[^>]*?)port="\d+"([^>]*?protocol="HTTP\/1\.1")/g,
            `$1port="${httpPort}"$2`
        );
        fs.writeFileSync(serverXmlPath, serverXml, 'utf8');
    }
}

// ---------------------------------------------------------------------------
// Context XML (conf/Catalina/localhost/[context].xml)
// ---------------------------------------------------------------------------

export function writeContextXml(opts: ConfigWriterOptions): void {
    const { tomcatBaseDir, contextPath, resolvedDocBase, resolvedSourceBase, resolvedClassesBase, jndiResources } = opts;
    const catalinaHostDir = path.join(tomcatBaseDir, 'conf', 'Catalina', 'localhost');

    if (fs.existsSync(catalinaHostDir)) {
        fs.rmSync(catalinaHostDir, { recursive: true, force: true });
    }
    fs.mkdirSync(catalinaHostDir, { recursive: true });

    const contextFileName = (contextPath === '/' || contextPath === '')
        ? 'ROOT.xml'
        : contextPath.replace(/^\//, '').replace(/\//g, '#') + '.xml';

    const content = buildContextXmlContent(resolvedDocBase, resolvedSourceBase, resolvedClassesBase, jndiResources);
    fs.writeFileSync(path.join(catalinaHostDir, contextFileName), content, 'utf8');
}

function buildContextXmlContent(
    resolvedDocBase: string,
    resolvedSourceBase: string,
    resolvedClassesBase: string,
    jndiResources: any[]
): string {
    const preResourcesXml = buildPreResourcesXml(resolvedSourceBase, resolvedClassesBase);
    const metaInfContextBody = readMetaInfContextBody(resolvedDocBase, resolvedSourceBase);
    const jndiResourcesXml = buildJndiResourcesXml(jndiResources);

    return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Auto-generated by happy-spring-tomcat extension.
  NOTE: conf/Catalina/localhost/*.xml takes precedence over META-INF/context.xml.
  Contents of META-INF/context.xml are embedded below automatically.
-->
<Context docBase="${resolvedDocBase}"
         reloadable="false"
         clearReferencesObjectStreamClassCaches="false"
         clearReferencesThreadLocals="false">${preResourcesXml}${metaInfContextBody}${jndiResourcesXml}
</Context>
`;
}

function buildPreResourcesXml(resolvedSourceBase: string, resolvedClassesBase: string): string {
    if (!resolvedSourceBase && !resolvedClassesBase) { return ''; }

    const preResList: string[] = [];
    if (resolvedSourceBase) {
        preResList.push(
            `        <PreResources className="org.apache.catalina.webresources.DirResourceSet"\n                      base="${resolvedSourceBase}"\n                      webAppMount="/" />`
        );
    }
    if (resolvedClassesBase) {
        preResList.push(
            `        <PreResources className="org.apache.catalina.webresources.DirResourceSet"\n                      base="${resolvedClassesBase}"\n                      webAppMount="/WEB-INF/classes" />`
        );
    }
    return `\n    <!-- Source Folder Mapping for Hot Reload -->\n    <Resources cachingAllowed="false" trackLockedFiles="true">\n${preResList.join('\n')}\n    </Resources>\n`;
}

function readMetaInfContextBody(resolvedDocBase: string, resolvedSourceBase: string): string {
    const candidates = [
        path.join(resolvedDocBase, 'META-INF', 'context.xml'),
        path.join(resolvedSourceBase, 'META-INF', 'context.xml'),
    ];
    for (const candidate of candidates) {
        if (fs.existsSync(candidate)) {
            const raw = fs.readFileSync(candidate, 'utf8');
            const innerMatch = raw.match(/<Context[^>]*>([\s\S]*?)<\/Context>/i);
            if (innerMatch && innerMatch[1].trim()) {
                return `\n    <!-- From META-INF/context.xml: ${candidate} -->${innerMatch[1]}`;
            }
            break;
        }
    }
    return '';
}

function buildJndiResourcesXml(jndiResources: any[]): string {
    if (!jndiResources || jndiResources.length === 0) { return ''; }

    const resourceElements = jndiResources.map((res: any) => {
        const attrs = Object.entries(res)
            .map(([key, value]) => `${key}="${value}"`)
            .join('\n               ');
        return `    <!-- JNDI DataSource (from settings) -->\n    <Resource ${attrs} />`;
    });
    return '\n' + resourceElements.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Scripts (.bat / .ps1 / .sh)  [Item 7: cross-platform]
// ---------------------------------------------------------------------------

export function writeScripts(opts: ConfigWriterOptions): void {
    const { vscodeDir, tomcatHome, tomcatBaseDir, httpPort, debugPort, contextPath, javaOpts, colorizeLogs } = opts;
    const extensionDir = path.join(vscodeDir, 'happy-spring-tomcat');

    if (!fs.existsSync(extensionDir)) {
        fs.mkdirSync(extensionDir, { recursive: true });
    }

    // --- Windows scripts ---
    fs.writeFileSync(path.join(extensionDir, 'colorize-logs.ps1'), '\uFEFF' + buildColorizePs1(), 'utf8');
    fs.writeFileSync(path.join(extensionDir, 'start-tomcat.bat'), buildStartBat({ tomcatHome, tomcatBaseDir, httpPort, debugPort, contextPath, javaOpts, colorizeLogs }), 'utf8');
    fs.writeFileSync(path.join(extensionDir, 'stop-tomcat.bat'), buildStopBat(httpPort, debugPort), 'utf8');

    // --- Mac/Linux scripts ---
    fs.writeFileSync(path.join(extensionDir, 'colorize-logs.awk'), buildColorizeAwk(), 'utf8');
    const startShPath = path.join(extensionDir, 'start-tomcat.sh');
    const stopShPath = path.join(extensionDir, 'stop-tomcat.sh');
    fs.writeFileSync(startShPath, buildStartSh({ tomcatHome, tomcatBaseDir, httpPort, debugPort, contextPath, javaOpts, colorizeLogs }), 'utf8');
    fs.writeFileSync(stopShPath, buildStopSh(httpPort, debugPort), 'utf8');

    try {
        fs.chmodSync(startShPath, '755');
        fs.chmodSync(stopShPath, '755');
    } catch {
        // chmod not supported on Windows — safe to ignore
    }
}

function buildColorizePs1(): string {
    return `$currentColor = "White"
$esc = [char]27
$input | ForEach-Object {
    $line = $_ -replace "\\x1b\\[[0-9;]*m",""
    
    $isNewEntry = $line -match '^(\\[?\\d{4}-\\d{2}-\\d{2}\\s|\\[?\\d{2}-\\w{3}-\\d{4}\\s|\\w{3}\\s\\d{2},\\s\\d{4})'
    
    if ($isNewEntry) {
        switch -Regex -CaseSensitive ($line) {
            '\\b(FATAL|CRITICAL)\\b' { $currentColor = "Magenta"; break }
            '\\b(ERROR|SEVERE)\\b|Exception\\b|Error\\b|심각' { $currentColor = "Red"; break }
            '\\b(WARN|WARNING|Potential)\\b|경고' { $currentColor = "Yellow"; break }
            '\\b(SQL|QUERY|sqltiming|HikariPool)\\b|Preparing:|Parameters:' { $currentColor = "DarkYellow"; break }
            '\\b(HTTP|REQUEST|RESPONSE|Mapping|Dispatching)\\b' { $currentColor = "Green"; break }
            '\\b(INFO|Started|Initializing)\\b|정보' { $currentColor = "Cyan"; break }
            '\\b(DEBUG|debug)\\b' { $currentColor = "Blue"; break }
            '\\b(TRACE|trace)\\b' { $currentColor = "DarkCyan"; break }
            default { $currentColor = "White" }
        }
        Write-Host $_ -ForegroundColor $currentColor
    } else {
        Write-Host "$esc[2m$_$esc[0m" -ForegroundColor $currentColor
    }
}`;
}

function buildColorizeAwk(): string {
    return `BEGIN {
    c_reset = "\\033[0m"
    c_dim = "\\033[2m"
    c_magenta = "\\033[35m"
    c_red = "\\033[31m"
    c_yellow = "\\033[33m"
    c_green = "\\033[32m"
    c_cyan = "\\033[36m"
    c_blue = "\\033[34m"
    c_orange = "\\033[38;5;208m"
    c_white = "\\033[37m"
    current_color = c_white
}
{
    line = $0
    sub(/^\\xef\\xbb\\xbf/, "", line)
    gsub(/\\033\\[[0-9;]*m/, "", line)
    
    if (line ~ /^(\\[?[0-9]{4}-[0-9]{2}-[0-9]{2} |\\[?[0-9]{2}-[a-zA-Z]{3}-[0-9]{4} |\\[?[a-zA-Z]{3} [0-9]{2}, [0-9]{4})/) {
        if (line ~ /FATAL|CRITICAL/) { current_color = c_magenta }
        else if (line ~ /ERROR|SEVERE|Exception|Error|심각/) { current_color = c_red }
        else if (line ~ /WARN|WARNING|Potential|경고/) { current_color = c_yellow }
        else if (line ~ /SQL|QUERY|sqltiming|HikariPool|Preparing:|Parameters:/) { current_color = c_orange }
        else if (line ~ /HTTP|REQUEST|RESPONSE|Mapping|Dispatching/) { current_color = c_green }
        else if (line ~ /INFO|Started|Initializing|정보/) { current_color = c_cyan }
        else if (line ~ /DEBUG|debug/) { current_color = c_blue }
        else if (line ~ /TRACE|trace/) { current_color = c_cyan }
        else { current_color = c_white }
        
        printf "%s%s%s\\n", current_color, line, c_reset
    } else {
        printf "%s%s%s%s\\n", current_color, c_dim, line, c_reset
    }
    fflush()
}`;
}

function buildStartBat(opts: {
    tomcatHome: string; tomcatBaseDir: string; httpPort: number; debugPort: number;
    contextPath: string; javaOpts: string; colorizeLogs: boolean;
}): string {
    const { tomcatHome, tomcatBaseDir, httpPort, debugPort, contextPath, javaOpts, colorizeLogs } = opts;
    const catalinaRunLine = colorizeLogs
        ? `call "%CATALINA_HOME%\\bin\\catalina.bat" jpda run 2>&1 | powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0colorize-logs.ps1"`
        : `call "%CATALINA_HOME%\\bin\\catalina.bat" jpda run`;

    return `@echo off
chcp 65001 > nul
echo ====================================================
echo Starting Tomcat in DEBUG mode (Port ${debugPort})...
echo HTTP Port: ${httpPort}
echo Context Path: ${contextPath}
echo ====================================================

echo Cleaning up previous Tomcat instances...
FOR /F "tokens=5" %%T IN ('netstat -a -n -o ^| findstr "LISTENING" ^| findstr ":${debugPort}"') DO (
    taskkill /F /PID %%T > nul 2>&1
)
FOR /F "tokens=5" %%T IN ('netstat -a -n -o ^| findstr "LISTENING" ^| findstr ":${httpPort}"') DO (
    taskkill /F /PID %%T > nul 2>&1
)
timeout /t 1 /nobreak > nul

set "JAVA_OPTS=${javaOpts}"
set "CATALINA_HOME=${tomcatHome}"
set "CATALINA_BASE=${tomcatBaseDir}"
set "JPDA_ADDRESS=127.0.0.1:${debugPort}"

echo Tomcat is launching (HTTP Port ${httpPort})...
${catalinaRunLine}

echo Tomcat process exited.
`;
}

function buildStopBat(httpPort: number, debugPort: number): string {
    return `@echo off
chcp 65001 > nul
echo ====================================================
echo Stopping Tomcat...
echo ====================================================

FOR /F "tokens=5" %%T IN ('netstat -a -n -o ^| findstr "LISTENING" ^| findstr ":${debugPort}"') DO (
    echo Killing debug port PID: %%T
    taskkill /F /PID %%T
)
FOR /F "tokens=5" %%T IN ('netstat -a -n -o ^| findstr "LISTENING" ^| findstr ":${httpPort}"') DO (
    echo Killing HTTP port PID: %%T
    taskkill /F /PID %%T
)
echo Tomcat stopped cleanly.
`;
}

function buildStartSh(opts: {
    tomcatHome: string; tomcatBaseDir: string; httpPort: number; debugPort: number;
    contextPath: string; javaOpts: string; colorizeLogs: boolean;
}): string {
    const { tomcatHome, tomcatBaseDir, httpPort, debugPort, contextPath, javaOpts, colorizeLogs } = opts;
    return `#!/bin/bash
# start-tomcat.sh — generated by happy-spring-tomcat extension
echo "==================================================="
echo "Starting Tomcat in DEBUG mode (Port ${debugPort})..."
echo "HTTP Port: ${httpPort}"
echo "Context Path: ${contextPath}"
echo "==================================================="

echo "Cleaning up previous Tomcat instances..."
lsof -ti :${debugPort} | xargs kill -9 2>/dev/null || true
lsof -ti :${httpPort} | xargs kill -9 2>/dev/null || true
sleep 1

export JAVA_OPTS="${javaOpts}"
export CATALINA_HOME="${tomcatHome}"
export CATALINA_BASE="${tomcatBaseDir}"
export JPDA_ADDRESS="127.0.0.1:${debugPort}"
export JPDA_TRANSPORT="dt_socket"

echo "Tomcat is launching (HTTP Port ${httpPort})..."
${colorizeLogs 
    ? `"$CATALINA_HOME/bin/catalina.sh" jpda run 2>&1 | awk -f "$(dirname "$0")/colorize-logs.awk"`
    : `"$CATALINA_HOME/bin/catalina.sh" jpda run`}
echo "Tomcat process exited."
`;
}

function buildStopSh(httpPort: number, debugPort: number): string {
    return `#!/bin/bash
# stop-tomcat.sh — generated by happy-spring-tomcat extension
echo "==================================================="
echo "Stopping Tomcat..."
echo "==================================================="

lsof -ti :${debugPort} | xargs kill -9 2>/dev/null || true
lsof -ti :${httpPort} | xargs kill -9 2>/dev/null || true
echo "Tomcat stopped cleanly."
`;
}

// ---------------------------------------------------------------------------
// tasks.json / launch.json
// ---------------------------------------------------------------------------

export function writeTasksJson(vscodeDir: string, preLaunchBuild: string = 'none'): void {
    const tasksJsonPath = path.join(vscodeDir, 'tasks.json');
    let tasksJson: any = { version: '2.0.0', tasks: [] };

    if (fs.existsSync(tasksJsonPath)) {
        try {
            const content = fs.readFileSync(tasksJsonPath, 'utf8');
            tasksJson = JSON.parse(content.replace(/\/\/.*|\/\*[\s\S]*?\*\//g, ''));
        } catch (e) { /* recreate */ }
    }

    if (!tasksJson.tasks) { tasksJson.tasks = []; }

    // Stop Tomcat task — platform-specific command
    const stopTaskDef: any = {
        label: STOP_TASK_NAME,
        type: 'shell',
        command: '${workspaceFolder}/.vscode/happy-spring-tomcat/stop-tomcat.sh',
        windows: { command: '${workspaceFolder}\\.vscode\\happy-spring-tomcat\\stop-tomcat.bat' },
        presentation: { reveal: 'silent', panel: 'shared', close: true, showReuseMessage: false }
    };

    // Start Tomcat task — platform-specific command + optional dependsOn
    const startTaskDef: any = {
        label: START_TASK_NAME,
        type: 'shell',
        command: '${workspaceFolder}/.vscode/happy-spring-tomcat/start-tomcat.sh',
        windows: { command: '${workspaceFolder}\\.vscode\\happy-spring-tomcat\\start-tomcat.bat' },
        isBackground: true,
        problemMatcher: {
            pattern: { regexp: '^$' },
            background: { activeOnStart: true, beginsPattern: 'Starting Tomcat', endsPattern: 'Server startup in' }
        },
        presentation: { reveal: 'always', panel: 'dedicated', group: 'tomcat', showReuseMessage: false }
    };

    // [Item 11] Pre-launch build tasks
    if (preLaunchBuild === 'maven') {
        upsertByLabel(tasksJson.tasks, 'Maven Build', {
            label: 'Maven Build',
            type: 'shell',
            command: 'mvn package -DskipTests',
            group: 'build',
            presentation: { reveal: 'always', panel: 'shared' }
        }, false);
        startTaskDef.dependsOn = ['Maven Build'];
    } else if (preLaunchBuild === 'gradle') {
        upsertByLabel(tasksJson.tasks, 'Gradle Build', {
            label: 'Gradle Build',
            type: 'shell',
            command: './gradlew build -x test',
            windows: { command: 'gradlew.bat build -x test' },
            group: 'build',
            presentation: { reveal: 'always', panel: 'shared' }
        }, false);
        startTaskDef.dependsOn = ['Gradle Build'];
    }

    upsertByLabel(tasksJson.tasks, STOP_TASK_NAME, stopTaskDef, true);
    upsertByLabel(tasksJson.tasks, START_TASK_NAME, startTaskDef, false);

    fs.writeFileSync(tasksJsonPath, JSON.stringify(tasksJson, null, 4), 'utf8');
}

export function writeLaunchJson(vscodeDir: string, debugPort: number, httpPort: number, contextPath: string, autoOpenBrowser: boolean): void {
    const launchJsonPath = path.join(vscodeDir, 'launch.json');
    let launchJson: any = { version: '0.2.0', configurations: [] };

    if (fs.existsSync(launchJsonPath)) {
        try {
            const content = fs.readFileSync(launchJsonPath, 'utf8');
            launchJson = JSON.parse(content.replace(/\/\/.*|\/\*[\s\S]*?\*\//g, ''));
        } catch (e) { /* ignore */ }
    }

    if (!launchJson.configurations) { launchJson.configurations = []; }

    const launchName = TOMCAT_DEBUG_CONFIG_NAME;
    const launchConfigDef: any = {
        type: 'java',
        name: launchName,
        request: 'attach',
        hostName: 'localhost',
        port: debugPort,
        preLaunchTask: START_TASK_NAME,
        postDebugTask: STOP_TASK_NAME,
        internalConsoleOptions: 'neverOpen'
    };

    // Note: serverReadyAction is intentionally omitted — it is not supported for
    // request: "attach" configurations. Browser auto-open is handled by the
    // extension itself via vscode.debug.onDidStartDebugSession + port polling.

    const idx = launchJson.configurations.findIndex((c: any) => c.name === launchName);
    if (idx >= 0) {
        launchJson.configurations[idx] = launchConfigDef;
    } else {
        launchJson.configurations.push(launchConfigDef);
    }

    fs.writeFileSync(launchJsonPath, JSON.stringify(launchJson, null, 4), 'utf8');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function upsertByLabel(arr: any[], label: string, def: any, prepend: boolean): void {
    const idx = arr.findIndex((t: any) => t.label === label);
    if (idx >= 0) {
        arr[idx] = def;
    } else if (prepend) {
        arr.unshift(def);
    } else {
        arr.push(def);
    }
}
