import * as fs from 'fs';
import * as path from 'path';
import { ConfigWriterOptions } from '../types';

export function writeContextXml(opts: ConfigWriterOptions): void {
    const { tomcatBaseDir, contextPath, resolvedDocBase, resolvedSourceBase, resolvedClassesBase, jndiResources } = opts;
    const catalinaHostDir = path.join(tomcatBaseDir, 'conf', 'Catalina', 'localhost');

    if (fs.existsSync(catalinaHostDir)) {
        fs.rmSync(catalinaHostDir, { recursive: true, force: true });
    }
    fs.mkdirSync(catalinaHostDir, { recursive: true });

    const contextFileName = (contextPath === '/' || contextPath === '')
        ? 'ROOT.xml'
        : contextPath.replace(/^\//, '').replace(/\//g, '#') + '.xml';

    const content = buildContextXmlContent(resolvedDocBase, resolvedSourceBase, resolvedClassesBase, jndiResources);
    fs.writeFileSync(path.join(catalinaHostDir, contextFileName), content, 'utf8');
}

function buildContextXmlContent(
    resolvedDocBase: string,
    resolvedSourceBase: string,
    resolvedClassesBase: string,
    jndiResources: any[]
): string {
    const preResourcesXml = buildPreResourcesXml(resolvedSourceBase, resolvedClassesBase);
    const metaInfContextBody = readMetaInfContextBody(resolvedDocBase, resolvedSourceBase);
    const jndiResourcesXml = buildJndiResourcesXml(jndiResources);

    return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Auto-generated by happy-spring-tomcat extension.
  NOTE: conf/Catalina/localhost/*.xml takes precedence over META-INF/context.xml.
  Contents of META-INF/context.xml are embedded below automatically.
-->
<Context docBase="${resolvedDocBase}"
         reloadable="false"
         clearReferencesObjectStreamClassCaches="false"
         clearReferencesThreadLocals="false">${preResourcesXml}${metaInfContextBody}${jndiResourcesXml}
</Context>
`;
}

function buildPreResourcesXml(resolvedSourceBase: string, resolvedClassesBase: string): string {
    if (!resolvedSourceBase && !resolvedClassesBase) { return ''; }

    const preResList: string[] = [];
    if (resolvedSourceBase) {
        preResList.push(
            `        <PreResources className="org.apache.catalina.webresources.DirResourceSet"\n                      base="${resolvedSourceBase}"\n                      webAppMount="/" />`
        );
    }
    if (resolvedClassesBase) {
        preResList.push(
            `        <PreResources className="org.apache.catalina.webresources.DirResourceSet"\n                      base="${resolvedClassesBase}"\n                      webAppMount="/WEB-INF/classes" />`
        );
    }
    return `\n    <!-- Source Folder Mapping for Hot Reload -->\n    <Resources cachingAllowed="false" trackLockedFiles="true">\n${preResList.join('\n')}\n    </Resources>\n`;
}

function readMetaInfContextBody(resolvedDocBase: string, resolvedSourceBase: string): string {
    const candidates = [
        path.join(resolvedDocBase, 'META-INF', 'context.xml'),
        path.join(resolvedSourceBase, 'META-INF', 'context.xml'),
    ];
    for (const candidate of candidates) {
        if (fs.existsSync(candidate)) {
            const raw = fs.readFileSync(candidate, 'utf8');
            const innerMatch = raw.match(/<Context[^>]*>([\s\S]*?)<\/Context>/i);
            if (innerMatch && innerMatch[1].trim()) {
                return `\n    <!-- From META-INF/context.xml: ${candidate} -->${innerMatch[1]}`;
            }
            break;
        }
    }
    return '';
}

function buildJndiResourcesXml(jndiResources: any[]): string {
    if (!jndiResources || jndiResources.length === 0) { return ''; }

    const resourceElements = jndiResources.map((res: any) => {
        const attrs = Object.entries(res)
            .map(([key, value]) => `${key}="${value}"`)
            .join('\n               ');
        return `    <!-- JNDI DataSource (from settings) -->\n    <Resource ${attrs} />`;
    });
    return '\n' + resourceElements.join('\n') + '\n';
}
